[twitch]
channel_id = "CHANNEL_ID"
client_id = "CLIENT_ID"
client_secret = "CLIENT_SECRET"
token = "TOKEN"
refresh_token = "REFRESH_TOKEN"

[authdb]
db = "auth.db"

[usersdb]
db = "users.db"

[pointsdb]
db = "points.db"
