[website]
# Password the user should use for /admin endpoints on the website.
admin_password = "ADMINISTRATOR_PASSWORD"

[twitch]
client_id = "CLIENT_ID"
client_secret = "CLIENT_SECRET"

[accountsdb]
db = "accounts.db"

[authdb]
db = "auth.db"

[usersdb]
db = "users.db"

[pointsdb]
db = "points.db"
